### ISSUE TITLE
Gallery page issue

### ISSUE THREAD

**Issue by GitHubMe78** [theonemule/gphoto-webui#1]
Hi Blaize,
Congratulation for this work.

I'm having a problem with the Gallery page.
When selected, I get:
[Wed Apr 1 22:52:38 2015] 192.168.4.64:51630 [200]: /service.php?action=getImages
sh: 1: exiv2: not found.
My camera is a Canon PowerShot A620 (PTP mode).
Any idea to solve that problem?
Merci.
Best regards

**Comment by theonemule** [comment]
Run this from the terminal and try again...

sudo apt-get install exiv2

**Comment by GitHubMe78** [comment]
Thanks,
It works fine!
